"""``verinoda pin``: a function's behaviour recorded while its tests run, written as a pytest file that passes.

Real child processes throughout (the experiment runner's throw-away copies). The orders_app copy is selected
through the index (static reach); the toy project names its tests. The generated file must pass on the current
tree, fail after a deliberate behaviour change in a copy, and leave out what does not replay the same.
"""

from __future__ import annotations

import os

os.environ.setdefault("GRAPHIFY_OUT", ".verinoda/index")

import ast  # noqa: E402
import datetime  # noqa: E402
import decimal  # noqa: E402
import fractions  # noqa: E402
import shutil  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402
from pathlib import Path  # noqa: E402

import pytest  # noqa: E402

from verinoda import experiments, paths, pin, workflow  # noqa: E402
from verinoda.runtime import pin_plugin as plug  # noqa: E402
from verinoda.store import open_store  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "orders_app"

experiment = [pytest.mark.experiment,
              pytest.mark.skipif(shutil.which("git") is None, reason="git not available"),
              pytest.mark.skipif(not hasattr(sys, "monitoring"), reason="the recorder needs sys.monitoring")]


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "-c", "core.autocrlf=false", *args],
                   cwd=cwd, check=True, capture_output=True, stdin=subprocess.DEVNULL)


def _commit(repo: Path) -> None:
    _git(repo, "init", "-q")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "init")


def _write(root: Path, files: dict[str, str]) -> None:
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))


def _run_file(repo: Path, rel: str) -> dict:
    st = open_store(repo, create=True)
    try:
        return experiments.run(st, repo, [experiments.python_for(repo), "-m", "pytest", "-q", rel],
                               hypothesis=f"the pinned tests in {rel} pass")
    finally:
        st.close()


@pytest.fixture(scope="module")
def orders(tmp_path_factory):
    repo = tmp_path_factory.mktemp("pin") / "orders_app"
    shutil.copytree(EXAMPLE, repo, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db"))
    _commit(repo)
    st = open_store(repo, create=True)
    workflow.scan(st, repo)
    res = pin.pin(st, repo, "orders/pricing.py::apply_discount")
    yield repo, st, res
    st.close()


# -- orders_app ---------------------------------------------------------------------------------------

def _marks(fn):
    for m in experiment:
        fn = m(fn)
    return fn


@_marks
def test_pinned_file_passes_on_the_current_tree_and_backs_an_experiment_verified_claim(orders):
    repo, st, res = orders
    assert res["status"] == "pinned", res
    assert res["generated"] == "tests/pinned/test_pin_apply_discount.py" and res["written"] is True
    assert res["selection"]["static"] >= 4 and "tests/test_pricing.py::test_compute_total" in res["tests"]
    assert res["cases"] == {"recorded": 4, "kept": 4, "dropped": {}}
    assert res["skipped_calls"] == {} and res["calls"] == 4
    assert res["replay_run"] == res["run_id"] and "confirm_run" not in res
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    head = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True,
                          stdin=subprocess.DEVNULL).stdout.strip()
    assert text.startswith(f"# Generated by verinoda pin at commit {head[:12]} ")
    assert "tests/test_pricing.py::test_discount_applies_above_threshold" in text.split("import", 1)[0]
    assert "orders.pricing.apply_discount(200.0)" in text and "_pin_expected = 180.0" in text
    assert text.count("\ndef test_apply_discount_pin_") == 4 and "\r" not in text
    ast.parse(text)
    # the replay that backs the claim ran exactly this file on a copy of the working tree
    exp = st.get("experiments", res["run_id"])
    assert exp["status"] == "pass" and exp["environment"]["source"]["added"] == [res["generated"]]
    assert res["claim"]["status"] == "experiment_verified"
    assert "behaviour on these 4 inputs is pinned at commit" in res["claim"]["text"]
    # and it passes again when run like any other test file
    assert _run_file(repo, res["generated"])["outcome"] == "pass"


@_marks
def test_pinned_file_fails_after_a_deliberate_behaviour_change(orders, tmp_path):
    repo, st, res = orders
    assert res["written"]
    copy = tmp_path / "changed"
    shutil.copytree(repo, copy, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db", ".git"))
    src = copy / "orders" / "pricing.py"
    src.write_bytes(src.read_bytes().replace(b"subtotal * 0.9", b"subtotal * 0.8"))
    run = _run_file(copy, res["generated"])
    assert run["outcome"] == "fail"
    assert "1 failed, 3 passed" in " ".join(run["summary"]["summary_lines"])


@_marks
def test_an_existing_file_is_kept_unless_forced(orders):
    repo, st, res = orders
    before = (repo / res["generated"]).read_bytes()
    again = pin.pin(st, repo, "orders/pricing.py::apply_discount")
    assert again["status"] == "refused" and "exists" in again["headline"] and "record_run" not in again
    assert (repo / res["generated"]).read_bytes() == before


@_marks
def test_an_untrusted_project_is_refused_and_nothing_is_written(tmp_path, monkeypatch):
    repo = tmp_path / "orders_app"
    shutil.copytree(EXAMPLE, repo, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db"))
    _commit(repo)
    monkeypatch.setenv(paths.CONFIG_DIR_ENV, str(tmp_path / "fresh-user-config"))
    monkeypatch.setattr(experiments, "container_runtime", lambda: None)
    assert not paths.is_trusted(repo)
    st = open_store(repo, create=True)
    try:
        res = pin.pin(st, repo, "orders/pricing.py::apply_discount", tests=["tests/test_pricing.py"])
    finally:
        st.close()
    assert res["status"] == "refused" and res["trusted"] is False and res["written"] is False
    assert "verinoda trust" in res["next_step"]
    assert not (repo / "tests" / "pinned").exists()


# -- a toy project: methods, enum, Decimal, nondeterminism ------------------------------------------

TOY = {
    "pyproject.toml": "[tool.pytest.ini_options]\npythonpath = [\".\"]\ntestpaths = [\"tests\"]\n",
    "toy/__init__.py": "",
    "toy/core.py": '''import enum
import random
from dataclasses import dataclass
from decimal import Decimal


class Tier(enum.Enum):
    GOLD = "gold"
    BASIC = "basic"


@dataclass
class Money:
    amount: Decimal
    currency: str = "EUR"

    def scaled(self, factor: int) -> "Money":
        return Money(self.amount * factor, self.currency)

    @staticmethod
    def parse(text: str) -> "Money":
        a, c = text.split()
        return Money(Decimal(a), c)

    @classmethod
    def zero(cls, currency: str) -> "Money":
        return cls(Decimal("0"), currency)


class Plain:
    def __init__(self, x):
        self.x = x

    def get(self):
        return self.x


def price(tier: Tier, base: Decimal) -> Decimal:
    if tier is Tier.GOLD:
        return base * Decimal("0.8")
    return base


def maybe(x):
    return x if x < 10 else x + random.random()


def handle(obj):
    return 1
''',
    "tests/test_core.py": '''from decimal import Decimal

from toy.core import Money, Tier, handle, maybe, price


def test_money():
    assert Money(Decimal("2.5")).scaled(2) == Money(Decimal("5.0"))
    assert Money.parse("3 USD").currency == "USD"
    assert Money.zero("TRY").amount == 0


def test_price():
    assert price(Tier.GOLD, Decimal("10")) == Decimal("8.0")
    assert price(Tier.BASIC, Decimal("10")) == Decimal("10")


def test_maybe():
    assert maybe(1) == 1
    assert maybe(50) >= 50
    assert maybe(50) >= 50
    assert maybe(70) >= 70


def test_handle():
    assert handle(object()) == 1
''',
}


@pytest.fixture(scope="module")
def toy(tmp_path_factory):
    repo = tmp_path_factory.mktemp("pin") / "toy"
    _write(repo, TOY)
    _commit(repo)
    st = open_store(repo, create=True)
    yield repo, st
    st.close()


def _pin(toy, sym: str, **kw) -> dict:
    repo, st = toy
    return pin.pin(st, repo, sym, tests=["tests/test_core.py"], **kw)


@_marks
def test_nondeterministic_inputs_are_dropped_and_the_rest_pinned(toy):
    repo, _ = toy
    res = _pin(toy, "toy/core.py::maybe")
    assert res["status"] == "pinned", res
    # maybe(50) gave two results in the recording run; maybe(70) one, which the replay did not reproduce
    assert res["cases"] == {"recorded": 3, "kept": 1,
                            "dropped": {pin.DROP_INCONSISTENT: 1, pin.DROP_REPLAY: 1}}
    assert res["confirm_run"] and res["run_id"] == res["confirm_run"] != res["replay_run"]
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    assert "toy.core.maybe(1)" in text and "maybe(50)" not in text and "maybe(70)" not in text
    assert _run_file(repo, res["generated"])["outcome"] == "pass"


@_marks
@pytest.mark.parametrize("sym, call, expected", [
    ("toy/core.py::Money.scaled", "toy.core.Money(amount=decimal.Decimal('2.5'), currency='EUR').scaled(2)",
     "toy.core.Money(amount=decimal.Decimal('5.0'), currency='EUR')"),
    ("toy/core.py::Money.parse", "toy.core.Money.parse('3 USD')",
     "toy.core.Money(amount=decimal.Decimal('3'), currency='USD')"),
    ("toy/core.py::Money.zero", "toy.core.Money.zero('TRY')",
     "toy.core.Money(amount=decimal.Decimal('0'), currency='TRY')"),
    ("toy/core.py::price", "toy.core.price(toy.core.Tier.GOLD, decimal.Decimal('10'))", "decimal.Decimal('8.0')"),
])
def test_methods_dataclasses_enums_and_decimals_are_pinned(toy, sym, call, expected):
    repo, _ = toy
    res = _pin(toy, sym, force=True)
    assert res["status"] == "pinned", res
    assert res["claim"]["status"] == "experiment_verified"
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    assert call in text and f"_pin_expected = {expected}" in text
    assert "import decimal" in text and "import toy.core" in text
    # files pinned earlier in this module are uncommitted changes of the tree the copies are made from
    assert res["uncommitted_changes"] == ("plus uncommitted changes (" in text.splitlines()[0])


@_marks
def test_calls_with_values_that_do_not_rebuild_are_skipped_with_the_reason(toy):
    repo, _ = toy
    res = _pin(toy, "toy/core.py::handle")
    assert res["status"] == "nothing_pinned" and res["written"] is False
    assert res["skipped_calls"] == {"unsupported type builtins.object": 1}
    assert not (repo / "tests" / "pinned" / "test_pin_handle.py").exists()


def test_instance_methods_of_other_classes_and_generators_are_unsupported_without_a_run(tmp_path):
    _write(tmp_path, {**TOY, "toy/gen.py": "def items(n):\n    yield from range(n)\n"})
    st = open_store(tmp_path, create=True)
    try:
        plain = pin.pin(st, tmp_path, "toy/core.py::Plain.get")
        gen = pin.pin(st, tmp_path, "toy/gen.py::items")
        test_code = pin.pin(st, tmp_path, "tests/test_core.py::test_price")
    finally:
        st.close()
    assert plain["status"] == "unsupported" and "not a dataclass" in plain["headline"]
    assert gen["status"] == "unsupported" and "generator" in gen["headline"]
    assert test_code["status"] == "unsupported" and "test code" in test_code["headline"]
    assert "record_run" not in plain and "record_run" not in gen


@pytest.mark.skipif(shutil.which("git") is None, reason="git not available")
def test_added_files_go_on_a_working_tree_copy_only(tmp_path):
    _write(tmp_path, {"a.py": "x = 1\n"})
    _commit(tmp_path)
    st = open_store(tmp_path, create=True)
    try:
        with pytest.raises(ValueError, match="working-tree copy only"):
            experiments.run(st, tmp_path, ["pytest", "-q"], hypothesis="x", ref="HEAD",
                            add_files={"tests/test_x.py": b""})
    finally:
        st.close()


def test_out_paths_must_stay_inside_the_repository():
    with pytest.raises(ValueError):
        pin._out_path("f", "../elsewhere/test_x.py")
    with pytest.raises(ValueError):
        pin._out_path("f", "tests/test_x.txt")
    assert pin._out_path("Money.zero", None) == "tests/pinned/test_pin_Money_zero.py"


# -- the value encoder (in-process: the plugin module is inert when imported by Verinoda) ---------

@pytest.mark.parametrize("value", [
    None, True, 3, -0.5, float("inf"), "a'b\n", b"\x00x", (1,), [1, (2.0, "x")], {"k": [1, {2}]},
    {3, 1, 2}, frozenset({"b", "a"}), set(), frozenset(), decimal.Decimal("1.10"), fractions.Fraction(1, 3),
    datetime.date(2024, 2, 29), datetime.datetime(2024, 1, 1, 12, 0, tzinfo=datetime.timezone.utc),
    datetime.timedelta(days=2, seconds=5), float("nan"),
])
def test_supported_values_rebuild_to_equal_values_of_the_same_type(value):
    imports: set = set()
    src = plug.value_source(value, imports)
    assert plug.same(plug.rebuild(src, imports), value)


def test_set_sources_do_not_depend_on_iteration_order():
    assert plug.value_source({"b", "a", "c"}, set()) == "{'a', 'b', 'c'}"


@pytest.mark.parametrize("value, reason", [
    (object(), "unsupported type builtins.object"),
    (complex(1, 2), "unsupported type builtins.complex"),
    (datetime.datetime(2024, 1, 1, tzinfo=datetime.timezone(datetime.timedelta(hours=3))), None),
    ([1, object()], "unsupported type builtins.object"),
    ("x" * (plug.MAX_LEN + 1), "str longer than"),
])
def test_other_values_are_skipped_with_a_reason(value, reason):
    if reason is None:  # a fixed-offset timezone is a datetime.timezone: supported
        assert plug.value_source(value, set())
        return
    with pytest.raises(plug._Skip, match=reason):
        plug.value_source(value, set())


def test_same_compares_types_all_the_way_down():
    assert not plug.same(1, 1.0) and not plug.same([1], [True]) and not plug.same((1,), [1])
    assert plug.same({"a": [float("nan")]}, {"a": [float("nan")]})


def test_exceptions_are_named_by_an_importable_type_and_their_message():
    imports: set = set()
    assert plug.exception_source(ValueError("bad"), imports) == ("ValueError", "bad") and imports == set()
    assert plug.exception_source(decimal.InvalidOperation("x"), imports)[0] == "decimal.InvalidOperation"
    with pytest.raises(plug._Skip, match="memory address"):
        plug.exception_source(RuntimeError("<object at 0x0000>"), set())
    with pytest.raises(plug._Skip, match="not an Exception"):
        plug.exception_source(KeyboardInterrupt(), set())
