"""Filter syntax in a query: path:, lang:, symbol:, is:, /regex/ and AND/OR/NOT narrow the ranked text search
(`verinoda query`, MCP project_query); a question without a filter ranks as before."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

os.environ.setdefault("GRAPHIFY_OUT", ".verinoda/index")

from verinoda import index, query_filters, retrieval, search_index, workflow  # noqa: E402
from verinoda.query_filters import FilterError, parse  # noqa: E402
from verinoda.store import open_store  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

CACHE = '''class PriceCache:
    """Keeps the price of an order for a while."""

    def take(self, key):
        return self.store.get(key)

    def put(self, key, price):
        self.store[key] = price


def price_of(order):
    # TODO: round the price of the order
    return order.total * 1.2
'''

LEGACY = '''def price_of_legacy(order):
    """The old way to compute the price of an order."""
    return order.total
'''

JAVA = '''package shop;

public class PriceService {
    public double priceOf(Order order) {
        return order.total() * 1.2;
    }
}
'''

VENDORED = '''def price_of_vendor(order):
    """A third-party price of an order."""
    return order.total
'''

GENERATED = '''# Code generated by protoc. DO NOT EDIT.
def price_of_generated(order):
    return order.total
'''

TESTS = '''from shop.cache import price_of


def test_price_of_an_order():
    assert price_of(type("O", (), {"total": 1})()) == 1.2
'''


def _write(root: Path, rel: str, text: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")


@pytest.fixture(scope="module")
def g(tmp_path_factory):
    root = tmp_path_factory.mktemp("qfilters") / "proj"
    _write(root, "shop/__init__.py", "")
    _write(root, "shop/cache.py", CACHE)
    _write(root, "shop/legacy.py", LEGACY)
    _write(root, "shop/gen_pb2.py", GENERATED)
    _write(root, "src/main/java/shop/PriceService.java", JAVA)
    _write(root, "third_party/pricing/vendor.py", VENDORED)
    _write(root, "tests/test_cache.py", TESTS)
    workflow.init(root)
    st = open_store(root)
    try:
        workflow.scan(st, root)
    finally:
        st.close()
    return index.load(root)


def _q(g, question, **kw):
    return retrieval.retrieve(g, question, retrieval.Budget(max_items=12, max_chars=20000), filters=True, **kw)


def _files(res) -> set[str]:
    return {i["file"] for i in res["items"]}


# -- reading the syntax ------------------------------------------------------------------------------

def test_a_question_without_a_filter_is_not_parsed():
    for q in ["where is the price of an order computed?", "why does take NOT return the price",
              "which handler serves /api/users/ now", "see http://example.com/x and C:/tmp"]:
        assert parse(q) is None


def test_filters_leave_the_rest_as_ranked_text():
    f = parse("price of an order path:shop/*.py lang:py")
    assert f.text == "price of an order" and f.describe() == "path:shop/*.py lang:py"
    f = parse("symbol:PriceCache.take cache")
    assert f.text == "PriceCache.take cache"   # a symbol name is ranked too (exact-identifier boost)
    assert parse("symbol:test_* price").text == "price"   # a glob is not


def test_operators_negation_groups_and_words_beside_an_operator():
    f = parse("(path:shop OR path:src) NOT is:test -lang:java price")
    assert f.describe() == "(path:shop OR path:src) NOT is:test NOT lang:java"
    assert f.text == "price"
    f = parse("cache OR memo lang:py")
    assert [a.kind for a in f.atoms] == ["word", "word", "lang"] and f.text == "cache memo"
    f = parse("NOT legacy lang:py price")
    assert f.text == "price" and "NOT legacy" in f.describe()   # a negated word is not ranked


def test_a_regex_is_read_whole_and_flags_are_kept():
    f = parse(r"/def\s+price_\w+/ where")
    assert f.atoms[0].kind == "regex" and f.atoms[0].value == r"def\s+price_\w+" and f.text == "where"
    f = parse("/TODO/i path:shop")
    assert str(f.atoms[0]) == "/TODO/i" and f.atoms[0].rx.search("todo")
    assert parse(r"/a\/b/ path:x").atoms[0].value == r"a\/b"


@pytest.mark.parametrize("q, msg", [("/(unclosed/ path:x", "not a regular expression"),
                                    ("is:weird price", "is:weird is not a filter"),
                                    ("path:a OR", "OR needs"), ("lang:py NOT", "NOT needs")])
def test_a_filter_that_cannot_be_read_is_an_error(q, msg):
    with pytest.raises(FilterError, match=msg):
        parse(q)


def test_path_lang_and_symbol_matching():
    pm, lm, sm = query_filters.path_matches, query_filters.lang_matches, query_filters.symbol_matches
    assert pm("shop/*.py", "shop/cache.py") and pm("*.py", "a/b/c.py") and pm("src/**/*.java", "src/A.java")
    assert pm("search_index", "verinoda/search_index.py") and pm("./Shop/", "shop/cache.py")
    assert pm("shop/", "src/main/java/shop/A.java") and not pm("hop/", "shop/cache.py")
    assert not pm("tests/", "shop/cache.py") and not pm("shop/*.java", "shop/cache.py")
    assert lm("py", "a.py") and lm("python", "a.pyi") and lm("kt", "A.kts") and lm("jvm", "A.java")
    assert lm("mcfunction", "data/x.mcfunction") and not lm("java", "a.py")
    assert sm("take", "take", "PriceCache.take") and sm("PriceCache.take", "take", "PriceCache.take")
    assert sm("price_*", "price_of", "price_of") and not sm("take", "put", "PriceCache.put")


# -- filters on the ranked search -----------------------------------------------------------------------

def test_without_filter_parsing_the_question_is_ranked_as_written(g):
    q = "price of an order path:shop/legacy.py"
    plain = retrieval.retrieve(g, q, retrieval.Budget(max_items=12, max_chars=20000))
    assert "filters" not in plain
    assert _files(plain) != {"shop/legacy.py"}


def test_a_path_filter_keeps_the_ranked_order_of_what_it_keeps(g):
    base = [i["id"] for i in retrieval.retrieve(g, "price of an order",
                                                retrieval.Budget(max_items=12, max_chars=20000))["items"]]
    res = _q(g, "price of an order path:shop/*")
    assert res["items"] and _files(res) <= {"shop/cache.py", "shop/legacy.py", "shop/gen_pb2.py", "shop/__init__.py"}
    kept = [i["id"] for i in res["items"]]
    assert [x for x in base if x in kept] == kept[:len([x for x in base if x in kept])]
    assert res["filters"] == {"expression": "path:shop/*", "ranked_text": "price of an order",
                              "matched": res["filters"]["matched"]} and res["filters"]["matched"] >= len(kept)


def test_lang_and_symbol_filters(g):
    assert _files(_q(g, "price of an order lang:java")) == {"src/main/java/shop/PriceService.java"}
    res = _q(g, "symbol:PriceCache.take")
    assert [i["symbol"] for i in res["items"]][:1] and all("take" in i["symbol"] for i in res["items"])
    assert len(res["items"]) == 1


def test_is_vendored_and_its_negation(g):
    assert _files(_q(g, "price of an order is:vendored")) == {"third_party/pricing/vendor.py", "shop/gen_pb2.py"}
    assert _files(_q(g, "price of an order is:generated")) == {"shop/gen_pb2.py"}
    rest = _files(_q(g, "price of an order NOT is:vendored NOT is:test"))
    assert rest and not rest & {"third_party/pricing/vendor.py", "shop/gen_pb2.py", "tests/test_cache.py"}


def test_or_between_filters(g):
    res = _q(g, "price of an order (lang:java OR path:legacy)")
    assert _files(res) == {"src/main/java/shop/PriceService.java", "shop/legacy.py"}


def test_a_regex_alone_lists_every_matching_unit_with_its_line(g):
    res = _q(g, "/TODO: round/")
    assert [i["file"] for i in res["items"]] == ["shop/cache.py"]
    it = res["items"][0]
    assert any(w == "regex /TODO: round/ at shop/cache.py:12" for w in it["why"])
    assert "TODO: round" in it["excerpt"] and it["lines"][0] <= 12 <= it["lines"][1]
    assert res["filters"]["ranked_text"] == ""
    text = retrieval.render_text(res, 6000)
    assert text.splitlines()[0].startswith("filters: /TODO: round/ (") and "TODO: round" in text


def test_words_beside_an_operator_are_content_filters(g):
    res = _q(g, "price NOT legacy path:shop/*")
    assert res["items"] and "shop/legacy.py" not in _files(res)
    res = _q(g, "store OR vendor lang:py")
    assert _files(res) and _files(res) <= {"shop/cache.py", "third_party/pricing/vendor.py"}


def test_no_match_is_said(g):
    res = _q(g, "price lang:rust")
    assert res["items"] == [] and res["filters"]["matched"] == 0
    assert "no indexed unit matches them" in retrieval.render_text(res, 6000)


def test_rank_where_hook_is_optional(g):
    a = search_index.rank(g, "price of an order")
    b = search_index.rank(g, "price of an order", where=lambda h, conn, uids: {u: ([], None) for u in uids})
    assert [x.key for x in a.hits] == [x.key for x in b.hits]


# -- CLI and MCP ----------------------------------------------------------------------------------------

def _cli(g, *args):
    env = dict(os.environ, PYTHONPATH=str(ROOT) + os.pathsep + os.environ.get("PYTHONPATH", ""),
               PYTHONIOENCODING="utf-8", GRAPHIFY_OUT=".verinoda/index")
    return subprocess.run([sys.executable, "-m", "verinoda", "query", *args, "--repo", str(g.root)], cwd=g.root,
                          env=env, capture_output=True, text=True, encoding="utf-8", timeout=240,
                          stdin=subprocess.DEVNULL, check=False)


def test_cli_query_reads_filters_and_reports_a_bad_one(g):
    r = _cli(g, "price of an order lang:java", "--json")
    assert r.returncode == 0, r.stderr
    res = json.loads(r.stdout)
    assert res["filters"]["expression"] == "lang:java"
    assert {i["file"] for i in res["items"]} == {"src/main/java/shop/PriceService.java"}
    bad = _cli(g, "price is:nonsense")
    assert bad.returncode != 0 and "is:nonsense is not a filter" in bad.stderr


def test_mcp_project_query_reads_filters(g):
    from verinoda.mcp.server import AtlasTools

    t = AtlasTools(g.root)
    res = t.project_query("price of an order lang:java", format="json")
    assert res["filters"]["expression"] == "lang:java", res
    err = t.project_query("price /(/ path:x")
    assert err["error"] == "invalid_argument" and "regular expression" in err["message"]
