"""``verinoda pin``: a function's behaviour recorded while its tests run, written as a pytest file that passes.

Real child processes throughout (the experiment runner's throw-away copies). The orders_app copy is selected
through the index (static reach); the toy project names its tests. The generated file must pass on the current
tree, fail after a deliberate behaviour change in a copy, and leave out what does not replay the same.
"""

from __future__ import annotations

import os

os.environ.setdefault("GRAPHIFY_OUT", ".verinoda/index")

import ast  # noqa: E402
import dataclasses  # noqa: E402
import datetime  # noqa: E402
import decimal  # noqa: E402
import fractions  # noqa: E402
import shutil  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402
from pathlib import Path  # noqa: E402

import pytest  # noqa: E402

from verinoda import experiments, paths, pin, workflow  # noqa: E402
from verinoda.runtime import pin_plugin as plug  # noqa: E402
from verinoda.store import open_store  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "orders_app"

experiment = [pytest.mark.experiment,
              pytest.mark.skipif(shutil.which("git") is None, reason="git not available"),
              pytest.mark.skipif(not hasattr(sys, "monitoring"), reason="the recorder needs sys.monitoring")]


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "-c", "core.autocrlf=false", *args],
                   cwd=cwd, check=True, capture_output=True, stdin=subprocess.DEVNULL)


def _commit(repo: Path) -> None:
    _git(repo, "init", "-q")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "init")


def _write(root: Path, files: dict[str, str]) -> None:
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))


def _run_file(repo: Path, rel: str) -> dict:
    st = open_store(repo, create=True)
    try:
        return experiments.run(st, repo, [experiments.python_for(repo), "-m", "pytest", "-q", rel],
                               hypothesis=f"the pinned tests in {rel} pass")
    finally:
        st.close()


@pytest.fixture(scope="module")
def orders(tmp_path_factory):
    repo = tmp_path_factory.mktemp("pin") / "orders_app"
    shutil.copytree(EXAMPLE, repo, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db"))
    _commit(repo)
    st = open_store(repo, create=True)
    workflow.scan(st, repo)
    res = pin.pin(st, repo, "orders/pricing.py::apply_discount")
    yield repo, st, res
    st.close()


# -- orders_app ---------------------------------------------------------------------------------------

def _marks(fn):
    for m in experiment:
        fn = m(fn)
    return fn


@_marks
def test_pinned_file_passes_on_the_current_tree_and_backs_an_experiment_verified_claim(orders):
    repo, st, res = orders
    assert res["status"] == "pinned", res
    assert res["generated"] == "tests/pinned/test_pin_orders_pricing__apply_discount.py" and res["written"] is True
    assert res["selection"]["static"] >= 4 and "tests/test_pricing.py::test_compute_total" in res["tests"]
    assert res["cases"] == {"recorded": 4, "kept": 4, "dropped": {}}
    assert res["skipped_calls"] == {} and res["calls"] == 4
    assert res["replay_run"] == res["run_id"] and "confirm_run" not in res
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    head = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True,
                          stdin=subprocess.DEVNULL).stdout.strip()
    assert text.startswith(f"# Generated by verinoda pin at commit {head[:12]} ")
    assert "tests/test_pricing.py::test_discount_applies_above_threshold" in text.split("import", 1)[0]
    assert "orders.pricing.apply_discount(200.0)" in text and "_pin_expected = 180.0" in text
    assert text.count("\ndef test_apply_discount_pin_") == 4 and "\r" not in text
    ast.parse(text)
    # the replay that backs the claim ran exactly this file on a copy of the working tree
    exp = st.get("experiments", res["run_id"])
    assert exp["status"] == "pass" and exp["environment"]["source"]["added"] == [res["generated"]]
    assert res["claim"]["status"] == "experiment_verified"
    assert "behaviour on these 4 inputs is pinned at commit" in res["claim"]["text"]
    # and it passes again when run like any other test file
    assert _run_file(repo, res["generated"])["outcome"] == "pass"


@_marks
def test_pinned_file_fails_after_a_deliberate_behaviour_change(orders, tmp_path):
    repo, st, res = orders
    assert res["written"]
    copy = tmp_path / "changed"
    shutil.copytree(repo, copy, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db", ".git"))
    src = copy / "orders" / "pricing.py"
    src.write_bytes(src.read_bytes().replace(b"subtotal * 0.9", b"subtotal * 0.8"))
    run = _run_file(copy, res["generated"])
    assert run["outcome"] == "fail"
    assert "1 failed, 3 passed" in " ".join(run["summary"]["summary_lines"])


@_marks
def test_an_existing_file_is_kept_unless_forced(orders):
    repo, st, res = orders
    before = (repo / res["generated"]).read_bytes()
    again = pin.pin(st, repo, "orders/pricing.py::apply_discount")
    assert again["status"] == "refused" and "exists" in again["headline"] and "record_run" not in again
    assert (repo / res["generated"]).read_bytes() == before


@_marks
def test_an_untrusted_project_is_refused_and_nothing_is_written(tmp_path, monkeypatch):
    repo = tmp_path / "orders_app"
    shutil.copytree(EXAMPLE, repo, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", "*.pyc", "*.db"))
    _commit(repo)
    monkeypatch.setenv(paths.CONFIG_DIR_ENV, str(tmp_path / "fresh-user-config"))
    monkeypatch.setattr(experiments, "container_runtime", lambda: None)
    assert not paths.is_trusted(repo)
    st = open_store(repo, create=True)
    try:
        res = pin.pin(st, repo, "orders/pricing.py::apply_discount", tests=["tests/test_pricing.py"])
    finally:
        st.close()
    assert res["status"] == "refused" and res["trusted"] is False and res["written"] is False
    assert "verinoda trust" in res["next_step"]
    assert not (repo / "tests" / "pinned").exists()


# -- a toy project: methods, enum, Decimal, nondeterminism ------------------------------------------

TOY = {
    "pyproject.toml": "[tool.pytest.ini_options]\npythonpath = [\".\"]\ntestpaths = [\"tests\"]\n",
    "toy/__init__.py": "",
    "toy/core.py": '''import enum
import random
from dataclasses import dataclass
from decimal import Decimal


class Tier(enum.Enum):
    GOLD = "gold"
    BASIC = "basic"


@dataclass
class Money:
    amount: Decimal
    currency: str = "EUR"

    def scaled(self, factor: int) -> "Money":
        return Money(self.amount * factor, self.currency)

    @staticmethod
    def parse(text: str) -> "Money":
        a, c = text.split()
        return Money(Decimal(a), c)

    @classmethod
    def zero(cls, currency: str) -> "Money":
        return cls(Decimal("0"), currency)


class Plain:
    def __init__(self, x):
        self.x = x

    def get(self):
        return self.x


def price(tier: Tier, base: Decimal) -> Decimal:
    if tier is Tier.GOLD:
        return base * Decimal("0.8")
    return base


def maybe(x):
    return x if x < 10 else x + random.random()


def handle(obj):
    return 1
''',
    "tests/test_core.py": '''from decimal import Decimal

from toy.core import Money, Tier, handle, maybe, price


def test_money():
    assert Money(Decimal("2.5")).scaled(2) == Money(Decimal("5.0"))
    assert Money.parse("3 USD").currency == "USD"
    assert Money.zero("TRY").amount == 0


def test_price():
    assert price(Tier.GOLD, Decimal("10")) == Decimal("8.0")
    assert price(Tier.BASIC, Decimal("10")) == Decimal("10")


def test_maybe():
    assert maybe(1) == 1
    assert maybe(50) >= 50
    assert maybe(50) >= 50
    assert maybe(70) >= 70


def test_handle():
    assert handle(object()) == 1
''',
}


@pytest.fixture(scope="module")
def toy(tmp_path_factory):
    repo = tmp_path_factory.mktemp("pin") / "toy"
    _write(repo, TOY)
    _commit(repo)
    st = open_store(repo, create=True)
    yield repo, st
    st.close()


def _pin(toy, sym: str, **kw) -> dict:
    repo, st = toy
    return pin.pin(st, repo, sym, tests=["tests/test_core.py"], **kw)


@_marks
def test_nondeterministic_inputs_are_dropped_and_the_rest_pinned(toy):
    repo, _ = toy
    res = _pin(toy, "toy/core.py::maybe")
    assert res["status"] == "pinned", res
    # maybe(50) gave two results in the recording run; maybe(70) one, which the replay did not reproduce
    assert res["cases"] == {"recorded": 3, "kept": 1,
                            "dropped": {pin.DROP_INCONSISTENT: 1, pin.DROP_REPLAY: 1}}
    assert res["confirm_run"] and res["run_id"] == res["confirm_run"] != res["replay_run"]
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    assert "toy.core.maybe(1)" in text and "maybe(50)" not in text and "maybe(70)" not in text
    assert _run_file(repo, res["generated"])["outcome"] == "pass"


@_marks
@pytest.mark.parametrize("sym, call, expected", [
    ("toy/core.py::Money.scaled", "toy.core.Money(amount=decimal.Decimal('2.5'), currency='EUR').scaled(2)",
     "toy.core.Money(amount=decimal.Decimal('5.0'), currency='EUR')"),
    ("toy/core.py::Money.parse", "toy.core.Money.parse('3 USD')",
     "toy.core.Money(amount=decimal.Decimal('3'), currency='USD')"),
    ("toy/core.py::Money.zero", "toy.core.Money.zero('TRY')",
     "toy.core.Money(amount=decimal.Decimal('0'), currency='TRY')"),
    ("toy/core.py::price", "toy.core.price(toy.core.Tier.GOLD, decimal.Decimal('10'))", "decimal.Decimal('8.0')"),
])
def test_methods_dataclasses_enums_and_decimals_are_pinned(toy, sym, call, expected):
    repo, _ = toy
    res = _pin(toy, sym, force=True)
    assert res["status"] == "pinned", res
    assert res["claim"]["status"] == "experiment_verified"
    text = (repo / res["generated"]).read_text(encoding="utf-8")
    assert call in text and f"_pin_expected = {expected}" in text
    assert "import decimal" in text and "import toy.core" in text
    # files pinned earlier in this module are uncommitted changes of the tree the copies are made from
    assert res["uncommitted_changes"] == ("plus uncommitted changes (" in text.splitlines()[0])


@_marks
def test_calls_with_values_that_do_not_rebuild_are_skipped_with_the_reason(toy):
    repo, _ = toy
    res = _pin(toy, "toy/core.py::handle")
    assert res["status"] == "nothing_pinned" and res["written"] is False
    assert res["skipped_calls"] == {"unsupported type builtins.object": 1}
    assert not (repo / "tests" / "pinned" / "test_pin_toy_core__handle.py").exists()


def test_instance_methods_of_other_classes_and_generators_are_unsupported_without_a_run(tmp_path):
    _write(tmp_path, {**TOY, "toy/gen.py": "def items(n):\n    yield from range(n)\n"})
    st = open_store(tmp_path, create=True)
    try:
        plain = pin.pin(st, tmp_path, "toy/core.py::Plain.get")
        gen = pin.pin(st, tmp_path, "toy/gen.py::items")
        test_code = pin.pin(st, tmp_path, "tests/test_core.py::test_price")
    finally:
        st.close()
    assert plain["status"] == "unsupported" and "not a dataclass" in plain["headline"]
    assert gen["status"] == "unsupported" and "generator" in gen["headline"]
    assert test_code["status"] == "unsupported" and "test code" in test_code["headline"]
    assert "record_run" not in plain and "record_run" not in gen


@pytest.mark.skipif(shutil.which("git") is None, reason="git not available")
def test_added_files_go_on_a_working_tree_copy_only(tmp_path):
    _write(tmp_path, {"a.py": "x = 1\n"})
    _commit(tmp_path)
    st = open_store(tmp_path, create=True)
    try:
        with pytest.raises(ValueError, match="working-tree copy only"):
            experiments.run(st, tmp_path, ["pytest", "-q"], hypothesis="x", ref="HEAD",
                            add_files={"tests/test_x.py": b""})
    finally:
        st.close()


def test_out_paths_must_stay_inside_the_repository():
    with pytest.raises(ValueError):
        pin._out_path("f", "../elsewhere/test_x.py")
    with pytest.raises(ValueError):
        pin._out_path("f", "tests/test_x.txt")
    assert pin._out_path("Money.zero", None, "toy/core.py") == "tests/pinned/test_pin_toy_core__Money__zero.py"


# -- the value encoder (in-process: the plugin module is inert when imported by Verinoda) ---------

@pytest.mark.parametrize("value", [
    None, True, 3, -0.5, float("inf"), "a'b\n", b"\x00x", (1,), [1, (2.0, "x")], {"k": [1, {2}]},
    {3, 1, 2}, frozenset({"b", "a"}), set(), frozenset(), decimal.Decimal("1.10"), fractions.Fraction(1, 3),
    datetime.date(2024, 2, 29), datetime.datetime(2024, 1, 1, 12, 0, tzinfo=datetime.timezone.utc),
    datetime.timedelta(days=2, seconds=5), float("nan"),
])
def test_supported_values_rebuild_to_equal_values_of_the_same_type(value):
    imports: set = set()
    src = plug.value_source(value, imports)
    assert plug.same(plug.rebuild(src, imports), value)


def test_set_sources_do_not_depend_on_iteration_order():
    assert plug.value_source({"b", "a", "c"}, set()) == "{'a', 'b', 'c'}"


@pytest.mark.parametrize("value, reason", [
    (object(), "unsupported type builtins.object"),
    (complex(1, 2), "unsupported type builtins.complex"),
    (datetime.datetime(2024, 1, 1, tzinfo=datetime.timezone(datetime.timedelta(hours=3))), None),
    ([1, object()], "unsupported type builtins.object"),
    ("x" * (plug.MAX_LEN + 1), "str longer than"),
])
def test_other_values_are_skipped_with_a_reason(value, reason):
    if reason is None:  # a fixed-offset timezone is a datetime.timezone: supported
        assert plug.value_source(value, set())
        return
    with pytest.raises(plug._Skip, match=reason):
        plug.value_source(value, set())


def test_same_compares_types_all_the_way_down():
    assert not plug.same(1, 1.0) and not plug.same([1], [True]) and not plug.same((1,), [1])
    assert plug.same({"a": [float("nan")]}, {"a": [float("nan")]})


def test_exceptions_are_named_by_an_importable_type_and_their_message():
    imports: set = set()
    assert plug.exception_source(ValueError("bad"), imports) == ("ValueError", "bad") and imports == set()
    assert plug.exception_source(decimal.InvalidOperation("x"), imports)[0] == "decimal.InvalidOperation"
    with pytest.raises(plug._Skip, match="memory address"):
        plug.exception_source(RuntimeError("<object at 0x0000>"), set())
    with pytest.raises(plug._Skip, match="not an Exception"):
        plug.exception_source(KeyboardInterrupt(), set())


# -- review round: strict comparison, the destination, what the recorder wrote, aliases -------------

@dataclasses.dataclass
class _P:
    x: int
    note: str = dataclasses.field(default="", compare=False)


def _generated_same():
    ns: dict = {"dataclasses": dataclasses}
    exec(pin.same_source(), ns)  # noqa: S102 - the helper text every generated file carries
    return ns["_pin_same"]


@pytest.mark.parametrize("before, after", [
    (-0.0, 0.0),
    (decimal.Decimal("3.00"), decimal.Decimal("3")),
    ({1.0}, {1}),
    (frozenset({True}), frozenset({1})),
    ({1.0: "v"}, {1: "v"}),
    (_P(1, "orig"), _P(1, "CHANGED")),
    ({"a": 1, "b": 2}, {"b": 2, "a": 1}),
    ([{"k": (decimal.Decimal("1.0"),)}], [{"k": (decimal.Decimal("1"),)}]),
])
def test_the_comparison_sees_changes_plain_equality_misses(before, after):
    assert before == after   # what the first version compared with
    for same in (plug.same, _generated_same()):
        assert not same(before, after) and same(before, before)


def test_the_generated_file_carries_the_recorders_comparison():
    text = pin.render("toy/core.py::f", "toy.core", "f", "function",
                      [{"call": {"self": None, "args": ["1"], "kwargs": []}, "imports": [], "outs": [{"r": "-0.0"}]}],
                      commit=None, tree=None)
    assert "def _pin_key(v):" in text and "import dataclasses" in text
    helpers = text.split("\n\n\ndef test_")[0].replace("import toy.core\n", "")
    ns: dict = {}
    exec(compile(helpers, "gen", "exec"), ns)  # noqa: S102 - imports and helpers only
    assert ns["_pin_same"](float("nan"), float("nan")) and not ns["_pin_same"](-0.0, 0.0)


SHAPES = '''import dataclasses
from decimal import Decimal


@dataclasses.dataclass
class P:
    x: int
    note: str = dataclasses.field(default="", compare=False)


def shapes(n):
    return (-0.0 * n, Decimal(n).quantize(Decimal("0.01")), {float(n)}, {float(n): "v"}, P(n, "orig"))
'''
SHAPES_MUTANTS = {
    "float sign": ("-0.0 * n", "0.0 * n"),
    "Decimal exponent": ('Decimal(n).quantize(Decimal("0.01"))', "Decimal(n)"),
    "set element type": ("{float(n)}, {", "{n}, {"),
    "dict key type": ('{float(n): "v"}', '{n: "v"}'),
    "dataclass field without compare": ('P(n, "orig")', 'P(n, "CHANGED")'),
}


@pytest.fixture(scope="module")
def shapes(tmp_path_factory):
    repo = tmp_path_factory.mktemp("pin") / "shapes"
    _write(repo, {**{k: v for k, v in TOY.items() if k != "tests/test_core.py"}, "toy/shapes.py": SHAPES,
                  "tests/test_shapes.py": "from toy.shapes import shapes\n\n\ndef test_shapes():\n"
                                          "    assert shapes(1)[0] == 0\n"})
    _commit(repo)
    st = open_store(repo, create=True)
    res = pin.pin(st, repo, "toy/shapes.py::shapes", tests=["tests/test_shapes.py"])
    yield repo, res
    st.close()


@_marks
@pytest.mark.parametrize("what", sorted(SHAPES_MUTANTS))
def test_pinned_file_fails_on_changes_equality_alone_misses(shapes, tmp_path, what):
    repo, res = shapes
    assert res["status"] == "pinned", res
    copy = tmp_path / "changed"
    shutil.copytree(repo, copy, ignore=shutil.ignore_patterns(".verinoda", "__pycache__", ".git"))
    old, new = SHAPES_MUTANTS[what]
    src = copy / "toy" / "shapes.py"
    assert old.encode() in src.read_bytes()
    src.write_bytes(src.read_bytes().replace(old.encode(), new.encode()))
    assert _run_file(copy, res["generated"])["outcome"] == "fail"


def _link_dir(link: Path, target: Path) -> None:
    if os.name == "nt":
        import _winapi
        _winapi.CreateJunction(str(target), str(link))   # no administrator rights needed
    else:
        os.symlink(target, link, target_is_directory=True)


def test_a_link_or_junction_on_the_way_is_refused_before_anything_runs(tmp_path):
    repo, outside = tmp_path / "repo", tmp_path / "outside"
    _write(repo, TOY)
    outside.mkdir()
    _link_dir(repo / "tests" / "jn", outside)
    with pytest.raises(ValueError, match="link or junction"):
        pin.check_dest(repo, "tests/jn/test_x.py")
    st = open_store(repo, create=True)
    try:
        res = pin.pin(st, repo, "toy/core.py::price", tests=["tests/test_core.py"], out="tests/jn/test_x.py")
    finally:
        st.close()
    assert res["status"] == "refused" and "record_run" not in res and not res["written"]
    assert list(outside.iterdir()) == []
    with pytest.raises(ValueError, match="link or junction"):
        pin.write_file(repo, "tests/jn/test_y.py", "toy/core.py::price", b"x = 1\n", force=False)
    assert list(outside.iterdir()) == []


@pytest.mark.parametrize("out", [".venv/Lib/site-packages/zz.py", ".github/x.py", "tests/x.py:ads", "a/../../x.py"])
def test_hidden_folders_and_odd_paths_are_refused(out):
    with pytest.raises(ValueError):
        pin._out_path("f", out, "toy/core.py")


def test_default_names_hold_the_module_and_force_replaces_only_this_functions_pin(tmp_path):
    assert pin.default_name("pkg_a/util.py", "parse") != pin.default_name("pkg_b/util.py", "parse")
    assert pin.default_name("m.py", "Cls.m") != pin.default_name("m.py", "Cls_m")
    _write(tmp_path, {"orders/api.py": "def handler():\n    return 1\n"})
    other = pin.render("pkg_a/util.py::parse", "pkg_a.util", "parse", "function",
                       [{"call": {"self": None, "args": ["1"], "kwargs": []}, "imports": [], "outs": [{"r": "1"}]}],
                       commit=None, tree=None)
    _write(tmp_path, {"tests/pinned/a.py": other})
    sym = "pkg_b/util.py::parse"
    assert "not generated by verinoda pin" in pin._destination_refused(tmp_path, "orders/api.py", sym, True)
    assert "pins another function" in pin._destination_refused(tmp_path, "tests/pinned/a.py", sym, True)
    assert "--force" in pin._destination_refused(tmp_path, "tests/pinned/a.py", "pkg_a/util.py::parse", False)
    assert pin._destination_refused(tmp_path, "tests/pinned/a.py", "pkg_a/util.py::parse", True) is None
    assert pin._destination_refused(tmp_path, "tests/pinned/new.py", sym, False) is None
    with pytest.raises(ValueError, match="not generated by verinoda pin"):
        pin.write_file(tmp_path, "orders/api.py", sym, b"x = 1\n", force=True)
    assert (tmp_path / "orders" / "api.py").read_bytes() == b"def handler():\n    return 1\n"
    pin.write_file(tmp_path, "tests/pinned/new.py", sym, b"x = 1\n", force=False)
    with pytest.raises(ValueError, match="--force"):
        pin.write_file(tmp_path, "tests/pinned/new.py", sym, b"y = 2\n", force=False)
    assert (tmp_path / "tests" / "pinned" / "new.py").read_bytes() == b"x = 1\n"


def test_force_on_a_production_module_is_refused_before_anything_runs(tmp_path):
    _write(tmp_path, TOY)
    st = open_store(tmp_path, create=True)
    try:
        res = pin.pin(st, tmp_path, "toy/core.py::price", tests=["tests/test_core.py"], out="toy/__init__.py",
                      force=True)
    finally:
        st.close()
    assert res["status"] == "refused" and "not generated by verinoda pin" in res["headline"]
    assert "record_run" not in res and (tmp_path / "toy" / "__init__.py").read_bytes() == b""


def _case(**kw):
    c = {"call": {"self": None, "args": ["1"], "kwargs": []}, "imports": [], "outs": [{"r": "1"}]}
    for k, v in kw.items():
        if k in ("args", "kwargs", "self"):
            c["call"][k] = v
        else:
            c[k] = v
    return c


@pytest.mark.parametrize("case, ok", [
    (_case(), True),
    (_case(imports=["decimal"], outs=[{"r": "decimal.Decimal('1.10')"}]), True),
    (_case(imports=["datetime"], args=["datetime.datetime(2024, 1, 1, tzinfo=datetime.timezone.utc)"]), True),
    (_case(args=["toy.core.Tier.GOLD", "toy.core.Money(amount=1, currency='EUR')"]), True),
    (_case(outs=[{"e": "ValueError", "m": "bad 'x'\n"}]), True),
    (_case(imports=["os; open('INJECTED_MARK', 'w').write('x')"]), False),
    (_case(imports=["os"], args=["os.system('x')"]), False),
    (_case(args=["__import__('os').getcwd()"]), False),
    (_case(args=["toy.core.price(1, 2)"]), False),
    (_case(args=["(lambda: 1)()"]), False),
    (_case(args=["1); import os; (1"]), False),
    (_case(outs=[{"r": "toy.core.__class__"}]), False),
    (_case(outs=[{"e": "ValueError) as x:\n    pass\nwith pytest.raises(ValueError", "m": ""}]), False),
    (_case(outs=[{"e": "print", "m": ""}]), False),
    (_case(kwargs=[["x", "open('f')"]]), False),
    (_case(self="toy.core.Money(amount=1)"), False),
])
def test_what_the_recorder_wrote_is_checked_before_it_is_written(tmp_path, case, ok):
    _write(tmp_path, TOY)
    check = pin.SourceCheck(tmp_path, ["toy/__init__.py", "toy/core.py"])
    assert check.case(case, "toy.core", "function") is ok


INJECT_CONFTEST = '''import json
import os

import pytest


@pytest.hookimpl(trylast=True)
def pytest_unconfigure(config):
    path = os.path.join(os.environ.get("VERINODA_ARTIFACTS") or ".", "pin.jsonl")
    if os.environ.get("VERINODA_PIN_MODE") != "record" or not os.path.exists(path):
        return
    lines = []
    for raw in open(path, encoding="utf-8").read().splitlines():
        rec = json.loads(raw)
        if rec.get("k") == "case":
            rec["imports"] = ["os; open('INJECTED_MARK', 'w').write('x')"]
        lines.append(json.dumps(rec))
    open(path, "w", encoding="utf-8").write(chr(10).join(lines) + chr(10))
'''


@_marks
def test_a_tampered_recording_writes_nothing_into_the_tree(tmp_path):
    _write(tmp_path, {**TOY, "tests/conftest.py": INJECT_CONFTEST})
    _commit(tmp_path)
    st = open_store(tmp_path, create=True)
    try:
        res = pin.pin(st, tmp_path, "toy/core.py::price", tests=["tests/test_core.py"])
    finally:
        st.close()
    assert res["status"] == "nothing_pinned" and res["written"] is False, res
    assert res["cases"]["dropped"] == {pin.DROP_UNSAFE: 2}
    assert not (tmp_path / "tests" / "pinned").exists() and not (tmp_path / "INJECTED_MARK").exists()


def test_arguments_that_share_an_object_are_detected():
    a = [1]
    assert plug._shares_object([a, a]) and plug._shares_object([[a, a]]) and plug._shares_object([{"k": a}, a])
    p = _P(1)
    assert plug._shares_object([p, p])
    assert not plug._shares_object([[1], [1]]) and not plug._shares_object([(1,), (1,)])
    assert not plug._shares_object(["s", "s", 1, 1])
