"""Local change (Verinoda, D65): which files are vendored, minified or generated code.

Not in Graphify (docs/UPSTREAM.md "New in Verinoda"). ``extract.extract`` reduces such a file (a vendored or
generated file keeps its definitions but no call leaves it; a minified one keeps its file node only), and
``verinoda.guards.is_generated`` uses :func:`generated_header` so the graph and the decision guards agree about
what is generated. Only the standard library is imported: this module is read by the guards without the
extractor.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

# Folders that hold third-party code wherever they are (exact spelling: a product namespace `Vendor/` or
# `Vendors/` is not one of them)
THIRD_PARTY_DIRS = frozenset({"_vendor", "third_party", "third-party", "thirdparty"})
# `vendor/` holds third-party code at the scan root, beside the manifest of a tool that vendors into it, or
# below a static-asset folder (`static/js/vendor/jquery/`, Laravel's `public/vendor/`); elsewhere it may be a
# product namespace (Rails `app/controllers/vendor/`)
VENDOR_MANIFESTS = ("go.mod", "composer.json", "Gemfile", "Cargo.toml")
STATIC_ASSET_DIRS = frozenset({"static", "assets", "public", "wwwroot"})
# `deps/` beside an Elixir/Erlang project file at the root; `deps/` or `extern/` holding a git submodule
DEPS_MANIFESTS = ("mix.exs", "rebar.config")
SUBMODULE_DIRS = frozenset({"deps", "extern"})

MINIFIED_NAME = re.compile(r"\.(min|bundle)\.[cm]?js$", re.IGNORECASE)
MINIFIED_SUFFIXES = (".js", ".mjs", ".cjs", ".css")   # the content rule: script and style only, never data
MINIFIED_MIN_BYTES = 4096
MINIFIED_LONG_LINE = 1000     # a line longer than this is machine-written ...
MINIFIED_SHARE = 0.9          # ... and minified code holds at least 90 % of the head's bytes in such lines
_CODE_PUNCT = re.compile(rb"[(;]")   # a long line of code, not a data literal (numbers, base64, an SVG path)

HEAD_BYTES = 65536
HEAD_LINES = 40
# The body of a comment line: `//`, `#`, `/*`, ` *`, `--`, `;`, `%` (not a `#!` interpreter line)
_COMMENT_BODY = re.compile(r"^\s*(?://+!?|#+(?!!)|/\*+!?|\*+|--+|;+|%+)\s*(.*?)\s*(?:\*/\s*)?$")
# A generator's own marker, at the start of the comment body
_GENERATED_MARK = re.compile(
    r"^(?:Code generated .*\bDO NOT EDIT\b"              # Go (and others): // Code generated by x. DO NOT EDIT.
    r"|@generated(?:\s|$)"                               # @generated, @generated SignedSource<<...>>
    r"|This file is (?:automatically )?@generated(?:\s|$)"   # prost-build, Cargo
    r"|A Bison parser, made by\b"
    r"|A lexical scanner generated by flex\b"
    r"|Generated by the protocol buffer compiler\b)",
    re.IGNORECASE)
# A generic "this file is generated" sentence, at the start of the comment body; it counts only with a warning
# against editing somewhere in the head (Rails `db/schema.rb`: "... then regenerate this schema definition")
_GENERATED_SENTENCE = re.compile(
    r"^(?:(?:This|The) (?:file|code) (?:is|was|has been) (?:automatically |auto-?)generated\b"
    r"|(?:Auto-?generated|Automatically generated) (?:file|code|by)\b)",
    re.IGNORECASE)
_EDIT_WARNING = re.compile(r"do not (?:edit|modify)|don't (?:edit|modify)|regenerat|will be (?:lost|overwritten)",
                           re.IGNORECASE)


def generated_header(text: str) -> bool:
    """True when a comment among the first 40 lines of *text* is a code generator's header.

    The marker must open the comment (``// Code generated ... DO NOT EDIT.``, ``@generated``, ``A Bison parser,
    made by``, ``A lexical scanner generated by flex``, ``Generated by the protocol buffer compiler``), or the
    comment must open with "This file is auto-generated" / "Auto-generated by" and the head must warn against
    editing it. A comment that only mentions generated code (``# Emits the auto-generated code ...``) and a
    marker written in a string are not headers.
    """
    sentence = False
    warning = False
    for line in text.splitlines()[:HEAD_LINES]:
        m = _COMMENT_BODY.match(line)
        if m is None:
            continue
        body = m.group(1)
        if _GENERATED_MARK.match(body):
            return True
        if _GENERATED_SENTENCE.match(body):
            sentence = True
        if _EDIT_WARNING.search(body):
            warning = True
        if sentence and warning:
            return True
    return False


def _minified(path: Path, head: bytes) -> bool:
    """A script or style file whose head is mostly lines of code longer than 1,000 bytes."""
    if not path.name.lower().endswith(MINIFIED_SUFFIXES) or len(head) < MINIFIED_MIN_BYTES:
        return False
    long_code = 0
    for line in head.split(b"\n"):
        if len(line) > MINIFIED_LONG_LINE and len(_CODE_PUNCT.findall(line)) * 100 >= len(line):
            long_code += len(line)
    return long_code >= MINIFIED_SHARE * len(head)


def _rel_dirs(path: Path, root: Path | None) -> tuple[str, ...]:
    """The folders of *path* below *root*, from the paths as given (no symlink or junction is followed, and
    a path outside *root* has none: the folders above the scan root never count)."""
    if root is None:
        return () if path.is_absolute() else Path(path).parts[:-1]
    try:
        rel = os.path.relpath(path, root)
    except ValueError:          # another drive
        return ()
    parts = Path(rel).parts
    if not parts or parts[0] == os.pardir:
        return ()
    return parts[:-1]


def _submodule_paths(root: Path, cache: dict) -> tuple[str, ...]:
    key = ("gitmodules", str(root))
    if key not in cache:
        found: list[str] = []
        try:
            text = (Path(root) / ".gitmodules").read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        for m in re.finditer(r"^\s*path\s*=\s*(.+?)\s*$", text, re.MULTILINE):
            found.append(m.group(1).replace("\\", "/").strip("/"))
        cache[key] = tuple(found)
    return cache[key]


def _has_file(folder: Path, names: tuple[str, ...], cache: dict) -> bool:
    key = ("manifest", str(folder), names)
    if key not in cache:
        cache[key] = any(os.path.isfile(os.path.join(folder, n)) for n in names)
    return cache[key]


def vendored_dir(path: Path, root: Path | None = None, cache: dict | None = None) -> bool:
    """True when *path* lies in a third-party folder below *root* (see the folder rules above)."""
    cache = {} if cache is None else cache
    dirs = _rel_dirs(path, root)
    for i, part in enumerate(dirs):
        if part in THIRD_PARTY_DIRS:
            return True
        if part == "vendor":
            if i == 0 or any(d in STATIC_ASSET_DIRS for d in dirs[:i]):
                return True
            if root is not None and _has_file(Path(root).joinpath(*dirs[:i]), VENDOR_MANIFESTS, cache):
                return True
        if part in SUBMODULE_DIRS and root is not None:
            if part == "deps" and i == 0 and _has_file(Path(root), DEPS_MANIFESTS, cache):
                return True
            prefix = "/".join(dirs[:i + 1])
            if any(sm == prefix or sm.startswith(prefix + "/") for sm in _submodule_paths(Path(root), cache)):
                return True
    return False


def vendored_reason(path: Path, root: Path | None = None, cache: dict | None = None) -> str | None:
    """Why *path* is vendored, minified or generated code (``vendored``/``minified``/``generated``), or None.

    ``vendored``: a third-party folder below *root* (:func:`vendored_dir`). ``minified``: a ``.min.js`` /
    ``.bundle.js`` name, or a script or style file whose first 64 KiB are mostly lines of code over 1,000 bytes.
    ``generated``: a generator's header comment among the first 40 lines (:func:`generated_header`).
    *cache* (a dict) memoises the folder look-ups of one run.
    """
    if vendored_dir(path, root, cache):
        return "vendored"
    if MINIFIED_NAME.search(path.name):
        return "minified"
    try:
        with open(path, "rb") as fh:
            head = fh.read(HEAD_BYTES)
    except OSError:
        return None
    if _minified(path, head):
        return "minified"
    if generated_header(head.decode("utf-8", errors="replace")):
        return "generated"
    return None
